        <h2>
            <a href="">Subsurface v4.6.4-1031</a>
        </h2>
	<div class="row build-row no-children">
		<div class="col-lg-3 text-nowrap">
			<span class="h4">Fedora 26
			</span>
		</div>
		<div class="col-lg-2 text-nowrap">
			<a href="../tests_reports/v4.6.4-1031/Fedora_26/1508514647/index.html" target="_blank"><span class="h5">20/10/2017 15:50:47 (UTC)</span></a>
		</div>
		<div class="col-lg-7">
			<div class="progress build-dashboard" title="passed: 4
softfailed: 0
failed: 0
total: 4">
			<div class="progress-bar progress-bar-passed " style="width: 100%;">4 passed</div>
			<div class="progress-bar progress-bar-softfailed " style="width: 0%;">0 softfailed</div>
			<div class="progress-bar progress-bar-failed " style="width: 0%;">0 failed</div>
			<div class="progress-bar progress-bar-skipped " style="width: 0%;">0 skipped</div>

			</div>
		</div>
	</div>	<div class="row build-row no-children">
		<div class="col-lg-3 text-nowrap">
			<span class="h4">openSUSE Tumbleweed 20171010
			</span>
		</div>
		<div class="col-lg-2 text-nowrap">
			<a href="../tests_reports/v4.6.4-1031/openSUSE_Tumbleweed_20171010/1508513769/index.html" target="_blank"><span class="h5">20/10/2017 15:36:09 (UTC)</span></a>
		</div>
		<div class="col-lg-7">
			<div class="progress build-dashboard" title="passed: 4
softfailed: 0
failed: 0
total: 4">
			<div class="progress-bar progress-bar-passed " style="width: 100%;">4 passed</div>
			<div class="progress-bar progress-bar-softfailed " style="width: 0%;">0 softfailed</div>
			<div class="progress-bar progress-bar-failed " style="width: 0%;">0 failed</div>
			<div class="progress-bar progress-bar-skipped " style="width: 0%;">0 skipped</div>

			</div>
		</div>
	</div>