        <h2>
            <a href="">Subsurface v4.7.1-11</a>
        </h2>
	<div class="row build-row no-children">
		<div class="col-lg-3 text-nowrap">
			<span class="h4">openSUSE Leap 42.3
			</span>
		</div>
		<div class="col-lg-2 text-nowrap">
			<a href="../tests_reports/v4.7.1-11/openSUSE_Leap_42.3/1508855497/index.html" target="_blank"><span class="h5">24/10/2017 14:31:37 (UTC)</span></a>
		</div>
		<div class="col-lg-7">
			<div class="progress build-dashboard" title="passed: 4
softfailed: 0
failed: 0
total: 4">
			<div class="progress-bar progress-bar-passed " style="width: 100%;">4 passed</div>
			<div class="progress-bar progress-bar-softfailed " style="width: 0%;">0 softfailed</div>
			<div class="progress-bar progress-bar-failed " style="width: 0%;">0 failed</div>
			<div class="progress-bar progress-bar-skipped " style="width: 0%;">0 skipped</div>

			</div>
		</div>
	</div>